Repository SSU-Plector/SSU-Plector-Backend, pull requests merged in 2024-04, with the labels that each got.

#26 ✨ [Feat] 프로젝트-유저 연결 API 구현
  src/main/java/ssuPlector/controller/ProjectDeveloperController.java
  src/main/java/ssuPlector/domain/Project.java
  src/main/java/ssuPlector/domain/ProjectUser.java
  src/main/java/ssuPlector/repository/projectUser/ProjectUserRepository.java
  src/main/java/ssuPlector/repository/user/UserRepository.java
  src/main/java/ssuPlector/service/projectDeveloper/ProjectDeveloperService.java
  src/main/java/ssuPlector/service/projectDeveloper/ProjectDeveloperServiceImpl.java
Labels: :sparkles: Feat

#30 ✨ [Feat] 개발자 생성 API 구현
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/converter/DeveloperConverter.java
  src/main/java/ssuPlector/domain/Developer.java
  src/main/java/ssuPlector/dto/request/DeveloperDTO.java
  src/main/java/ssuPlector/global/response/code/GlobalErrorCode.java
  src/main/java/ssuPlector/service/developer/DeveloperService.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
  src/main/java/ssuPlector/service/project/ProjectServiceImpl.java
Labels: :sparkles: Feat, :recycle: Refactor

#32 ♻️ [Refactor] list 사이즈 확인 어노테이션 추가 및 검증
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/controller/ProjectController.java
  src/main/java/ssuPlector/controller/ProjectDeveloperController.java
  src/main/java/ssuPlector/converter/DeveloperConverter.java
  src/main/java/ssuPlector/converter/ProjectConverter.java
  src/main/java/ssuPlector/domain/Project.java
  src/main/java/ssuPlector/dto/request/DeveloperDTO.java
  src/main/java/ssuPlector/dto/request/ProjectDTO.java
  src/main/java/ssuPlector/dto/response/ProjectDTO.java
  src/main/java/ssuPlector/global/exception/ExceptionAdvice.java
  src/main/java/ssuPlector/global/response/code/GlobalErrorCode.java
  src/main/java/ssuPlector/validation/annotation/MaxSizeThree.java
  src/main/java/ssuPlector/validation/annotation/MaxSizeTwo.java
  src/main/java/ssuPlector/validation/validator/MaxSizeThreeValidator.java
  src/main/java/ssuPlector/validation/validator/MaxSizeTwoValidator.java
Labels: :sparkles: Feat, :recycle: Refactor

#33 ♻️ [Refactor] 단일 이미지, 페이지 사이즈, 개발자-프로젝트 연결 api 수정
  src/main/java/ssuPlector/controller/ProjectDeveloperController.java
  src/main/java/ssuPlector/converter/DeveloperConverter.java
  src/main/java/ssuPlector/converter/ImageConverter.java
  src/main/java/ssuPlector/converter/ProjectConverter.java
  src/main/java/ssuPlector/domain/Developer.java
  src/main/java/ssuPlector/domain/Image.java
  src/main/java/ssuPlector/domain/Project.java
  src/main/java/ssuPlector/dto/request/DeveloperDTO.java
  src/main/java/ssuPlector/dto/request/ImageDTO.java
  src/main/java/ssuPlector/dto/request/ProjectDTO.java
  src/main/java/ssuPlector/dto/response/DeveloperDTO.java
  src/main/java/ssuPlector/dto/response/ImageDTO.java
  src/main/java/ssuPlector/dto/response/ProjectDTO.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
  src/main/java/ssuPlector/service/project/ProjectServiceImpl.java
Labels: :sparkles: Feat, :recycle: Refactor

#37 ✨ [Feat] 개발자, 프로젝트 이미지 S3 업로드 기능 추가
  build.gradle
  src/main/java/ssuPlector/aws/s3/AmazonS3Manager.java
  src/main/java/ssuPlector/config/AmazonConfig.java
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/controller/ProjectController.java
  src/main/java/ssuPlector/domain/Uuid.java
  src/main/java/ssuPlector/dto/request/DeveloperDTO.java
  src/main/java/ssuPlector/dto/request/ProjectDTO.java
  src/main/java/ssuPlector/global/MultipartJackson2HttpMessageConverter.java
  src/main/java/ssuPlector/repository/UuidRepository.java
  src/main/java/ssuPlector/service/developer/DeveloperService.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
  src/main/java/ssuPlector/service/project/ProjectService.java
  src/main/java/ssuPlector/service/project/ProjectServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: Feat, :recycle: Refactor

#36 ✨ [Feat] 개발자 목록 조회 API 구현
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/converter/DeveloperConverter.java
  src/main/java/ssuPlector/dto/request/DeveloperDTO.java
  src/main/java/ssuPlector/dto/response/DeveloperDTO.java
  src/main/java/ssuPlector/dto/response/ProjectDTO.java
  src/main/java/ssuPlector/repository/developer/DeveloperRepository.java
  src/main/java/ssuPlector/repository/developer/DeveloperRepositoryCustom.java
  src/main/java/ssuPlector/repository/developer/DeveloperRepositoryImpl.java
  src/main/java/ssuPlector/service/developer/DeveloperService.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
Labels: :sparkles: Feat

#46 [Fix] CI/CD 누락 코드 추가
  build.gradle
Labels: :bug: Bug

#47 [Fix] CI/CD 버그 수정
  .github/workflows/dev_deploy.yml
Labels: :bug: Bug

#48 [Fix] CI/CD 버그 수정
  .github/workflows/dev_deploy.yml
Labels: :bug: Bug
