Repository SSU-Plector/SSU-Plector-Backend, pull requests merged in 2024-06, with the labels that each got.

#104 :recycle: [Refactor] 회원탈퇴 시developerId 입력 -> @Authuser로 developer를 반환하는 방식으로 수정
  src/main/java/ssuPlector/controller/AuthController.java
Labels: :recycle: Refactor

#106 :recycle: [Refactor] null -> emptylist 변경
  src/main/java/ssuPlector/controller/AuthController.java
  src/main/java/ssuPlector/global/response/ApiResponse.java
Labels: :recycle: Refactor

#107 :recycle: [Refactor] null -> {} 변경
  src/main/java/ssuPlector/controller/AuthController.java
  src/main/java/ssuPlector/global/response/ApiResponse.java
  src/main/java/ssuPlector/security/filter/AuthExceptionHandlingFilter.java
  src/main/java/ssuPlector/security/handler/JwtAccessDeniedHandler.java
  src/main/java/ssuPlector/security/handler/JwtAuthenticationEntryPoint.java
Labels: :recycle: Refactor, :bug: Bug

#109 [Fix] 데이터베이스 테이블 생성
  src/main/resources/application.yml
Labels: :bug: Bug

#110 [Refactor] yml 파일 데이터베이스 update으로 수정
  src/main/resources/application.yml
Labels: :bug: Bug

#114 [Hotfix] 프로젝트 대표 이미지 없을 때 첫 번째 이미지 리턴
  src/main/java/ssuPlector/dto/response/ProjectDTO.java
Labels: 🚑 !HOTFIX

#112 :ambulance: [Fix] 프로젝트에서 개발자 조회시 NULL 리턴 해결
  src/main/java/ssuPlector/converter/DeveloperConverter.java
Labels: 🚑 !HOTFIX

#117 [fix] 탈퇴한 회원 포함 조회 쿼리 오류 수정
  src/main/java/ssuPlector/repository/developer/DeveloperRepository.java
Labels: :bug: Bug

#118 [fix] 탈퇴한 회원 포함 조회 쿼리 오류 수정
  src/main/java/ssuPlector/repository/developer/DeveloperRepository.java
Labels: :bug: Bug

#121 [fix] 탈퇴한 회원 포함 조회 쿼리 오류 수정
  src/main/java/ssuPlector/repository/developer/DeveloperRepository.java
Labels: :bug: Bug
