Repository SSU-Plector/SSU-Plector-Backend, pull requests merged in 2024-03, with the labels that each got.

#2 :construction_worker: [CI] 코드컨벤션 적용 세팅
  .gitignore
  .script/pre-commit
  build.gradle
Labels: 👷 ci

#5 :sparkles: [Feat] swagger 라이브러리 추가 및 설정
  build.gradle
  src/main/java/ssuPlector/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: :sparkles: Feat, :memo: Docs

#7 ✨ [Feat] ApiResponse 클래스 추가 및 전역 예외 처리 핸들러 추가
  src/main/java/ssuPlector/global/exception/ExceptionAdvice.java
  src/main/java/ssuPlector/global/exception/GlobalException.java
  src/main/java/ssuPlector/global/response/ApiResponse.java
  src/main/java/ssuPlector/global/response/code/GlobalErrorCode.java
  src/main/java/ssuPlector/global/response/code/SuccessCode.java
Labels: :sparkles: Feat, :memo: Docs

#10 ✨ [Feat] Querydsl 라이브러리 추가 및 설정
  .gitignore
  build.gradle
  src/main/java/ssuPlector/config/QuerydslConfig.java
Labels: :sparkles: Feat, :memo: Docs

#9 Issue/3 domain
  src/main/java/ssuPlector/Category.java
  src/main/java/ssuPlector/Image.java
  src/main/java/ssuPlector/Part.java
  src/main/java/ssuPlector/Project.java
  src/main/java/ssuPlector/ProjectUser.java
  src/main/java/ssuPlector/SsuPlectorApplication.java
  src/main/java/ssuPlector/User.java
  src/main/java/ssuPlector/domain/BaseEntity.java
  src/main/java/ssuPlector/domain/Image.java
  src/main/java/ssuPlector/domain/Project.java
  src/main/java/ssuPlector/domain/ProjectUser.java
  src/main/java/ssuPlector/domain/User.java
  src/main/java/ssuPlector/domain/category/Category.java
  src/main/java/ssuPlector/domain/category/DevLanguage.java
  src/main/java/ssuPlector/domain/category/DevTools.java
  src/main/java/ssuPlector/domain/category/Part.java
  src/main/java/ssuPlector/domain/category/TechStack.java
  src/test/java/ssuPlector/SsuPlectorApplicationTests.java
Labels: 🦴Domain

#19 [Feat] 프로젝트 조건 조회
  build.gradle
  src/main/java/ssuPlector/config/QuerydslConfig.java
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/controller/ProjectController.java
  src/main/java/ssuPlector/domain/BaseEntity.java
  src/main/java/ssuPlector/domain/Image.java
  src/main/java/ssuPlector/domain/Project.java
  src/main/java/ssuPlector/domain/ProjectUser.java
  src/main/java/ssuPlector/domain/User.java
  src/main/java/ssuPlector/dto/requestDto/ProjectListRequestDto.java
  src/main/java/ssuPlector/dto/responseDto/ProjectListResponseDto.java
  src/main/java/ssuPlector/repository/Image/ImageRepository.java
  src/main/java/ssuPlector/repository/project/ProjectRepository.java
  src/main/java/ssuPlector/repository/project/ProjectRepositoryCustom.java
  src/main/java/ssuPlector/repository/project/ProjectRepositoryCustomImpl.java
  src/main/java/ssuPlector/repository/projectUser/ProjectUserRepository.java
  src/main/java/ssuPlector/repository/user/UserRepository.java
  src/main/java/ssuPlector/service/developer/DeveloperService.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
  src/main/java/ssuPlector/service/project/ProjectService.java
  src/main/java/ssuPlector/service/project/ProjectServiceImpl.java
  src/test/java/ssuPlector/ProjectServiceTest.java
Labels: :sparkles: Feat

#20 ✨ [Feat] 개발자 상세조회 및 개발자 존재 여부확인 커스텀 어노테이션
  build.gradle
  src/main/java/ssuPlector/SsuPlectorApplication.java
  src/main/java/ssuPlector/config/RedisConfig.java
  src/main/java/ssuPlector/config/SchedulerConfig.java
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/controller/ProjectController.java
  src/main/java/ssuPlector/converter/ImageConverter.java
  src/main/java/ssuPlector/converter/ProjectConverter.java
  src/main/java/ssuPlector/converter/UserConverter.java
  src/main/java/ssuPlector/dto/request/ProjectDTO.java
  src/main/java/ssuPlector/dto/requestDto/ProjectListRequestDto.java
  src/main/java/ssuPlector/dto/response/DeveloperDTO.java
  src/main/java/ssuPlector/dto/response/ImageDTO.java
  src/main/java/ssuPlector/dto/response/ProjectDTO.java
  src/main/java/ssuPlector/dto/responseDto/ProjectListResponseDto.java
  src/main/java/ssuPlector/global/exception/ExceptionAdvice.java
  src/main/java/ssuPlector/global/response/code/GlobalErrorCode.java
  src/main/java/ssuPlector/redis/repository/DeveloperHitsRepository.java
  src/main/java/ssuPlector/redis/repository/Impl/DeveloperHitsRepositoryImpl.java
  src/main/java/ssuPlector/redis/repository/Impl/ProjectHitsRepositoryImpl.java
  src/main/java/ssuPlector/redis/repository/ProjectHitsRepository.java
  src/main/java/ssuPlector/redis/service/DeveloperHitsService.java
  src/main/java/ssuPlector/redis/service/Impl/DeveloperHitsServiceImpl.java
  src/main/java/ssuPlector/redis/service/Impl/ProjectHitsServiceImpl.java
  src/main/java/ssuPlector/redis/service/ProjectHitsService.java
  src/main/java/ssuPlector/repository/project/ProjectRepository.java
  src/main/java/ssuPlector/repository/user/UserRepository.java
  src/main/java/ssuPlector/service/developer/DeveloperService.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
  src/main/java/ssuPlector/service/project/ProjectService.java
  src/main/java/ssuPlector/service/project/ProjectServiceImpl.java
  src/main/java/ssuPlector/validation/annotation/ExistDeveloper.java
  src/main/java/ssuPlector/validation/annotation/ExistProject.java
  src/main/java/ssuPlector/validation/validator/ExistDeveloperValidator.java
  src/main/java/ssuPlector/validation/validator/ExistProjectValidator.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: :sparkles: Feat

#21 ✨ [Feat] 프로젝트 상세 조회 API 및 프로젝트 존재 여부 커스텀 어노테이션
  build.gradle
  src/main/java/ssuPlector/SsuPlectorApplication.java
  src/main/java/ssuPlector/config/RedisConfig.java
  src/main/java/ssuPlector/config/SchedulerConfig.java
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/controller/ProjectController.java
  src/main/java/ssuPlector/converter/ImageConverter.java
  src/main/java/ssuPlector/converter/ProjectConverter.java
  src/main/java/ssuPlector/converter/UserConverter.java
  src/main/java/ssuPlector/dto/request/ProjectDTO.java
  src/main/java/ssuPlector/dto/requestDto/ProjectListRequestDto.java
  src/main/java/ssuPlector/dto/response/DeveloperDTO.java
  src/main/java/ssuPlector/dto/response/ImageDTO.java
  src/main/java/ssuPlector/dto/response/ProjectDTO.java
  src/main/java/ssuPlector/dto/responseDto/ProjectListResponseDto.java
  src/main/java/ssuPlector/global/exception/ExceptionAdvice.java
  src/main/java/ssuPlector/global/response/code/GlobalErrorCode.java
  src/main/java/ssuPlector/redis/repository/DeveloperHitsRepository.java
  src/main/java/ssuPlector/redis/repository/Impl/DeveloperHitsRepositoryImpl.java
  src/main/java/ssuPlector/redis/repository/Impl/ProjectHitsRepositoryImpl.java
  src/main/java/ssuPlector/redis/repository/ProjectHitsRepository.java
  src/main/java/ssuPlector/redis/service/DeveloperHitsService.java
  src/main/java/ssuPlector/redis/service/Impl/DeveloperHitsServiceImpl.java
  src/main/java/ssuPlector/redis/service/Impl/ProjectHitsServiceImpl.java
  src/main/java/ssuPlector/redis/service/ProjectHitsService.java
  src/main/java/ssuPlector/repository/project/ProjectRepository.java
  src/main/java/ssuPlector/repository/user/UserRepository.java
  src/main/java/ssuPlector/service/developer/DeveloperService.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
  src/main/java/ssuPlector/service/project/ProjectService.java
  src/main/java/ssuPlector/service/project/ProjectServiceImpl.java
  src/main/java/ssuPlector/validation/annotation/ExistDeveloper.java
  src/main/java/ssuPlector/validation/annotation/ExistProject.java
  src/main/java/ssuPlector/validation/validator/ExistDeveloperValidator.java
  src/main/java/ssuPlector/validation/validator/ExistProjectValidator.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: :sparkles: Feat

#23 Isssue/13 spec project
  src/main/java/ssuPlector/controller/ProjectController.java
  src/main/java/ssuPlector/dto/request/ProjectDTO.java
  src/main/java/ssuPlector/global/response/code/GlobalErrorCode.java
  src/main/java/ssuPlector/service/project/ProjectServiceImpl.java
  src/test/java/ssuPlector/ProjectServiceTest.java
Labels: 🚑 !HOTFIX

#24 ✨ [Feat] 프로젝트 생성 및 저장 API 구현
  src/main/java/ssuPlector/controller/ProjectController.java
  src/main/java/ssuPlector/converter/ImageConverter.java
  src/main/java/ssuPlector/converter/ProjectConverter.java
  src/main/java/ssuPlector/converter/UserConverter.java
  src/main/java/ssuPlector/domain/Image.java
  src/main/java/ssuPlector/domain/Project.java
  src/main/java/ssuPlector/domain/ProjectUser.java
  src/main/java/ssuPlector/domain/User.java
  src/main/java/ssuPlector/domain/category/Category.java
  src/main/java/ssuPlector/domain/category/DevLanguage.java
  src/main/java/ssuPlector/domain/category/DevTools.java
  src/main/java/ssuPlector/domain/category/Part.java
  src/main/java/ssuPlector/domain/category/TechStack.java
  src/main/java/ssuPlector/dto/request/ImageDTO.java
  src/main/java/ssuPlector/dto/request/ProjectDTO.java
  src/main/java/ssuPlector/dto/response/ProjectDTO.java
  src/main/java/ssuPlector/global/exception/ExceptionAdvice.java
  src/main/java/ssuPlector/global/response/code/GlobalErrorCode.java
  src/main/java/ssuPlector/repository/user/UserRepository.java
  src/main/java/ssuPlector/service/project/ProjectService.java
  src/main/java/ssuPlector/service/project/ProjectServiceImpl.java
Labels: :sparkles: Feat, :recycle: Refactor, :bug: Bug
