Repository SSU-Plector/SSU-Plector-Backend, pull requests merged in 2024-05, with the labels that each got.

#49 [Fix] CI/CD 버그 수정
  .github/workflows/dev_deploy.yml
Labels: 👷 ci

#50 [Ci] CI/CD 버그 수정
  .github/workflows/dev_deploy.yml
Labels: 👷 ci

#51 ♻️ [Refactor] yml 파일 dev,local 분리
  src/main/resources/application.yml
Labels: :recycle: Refactor

#54 :recycle: [Refactor] yml 확장자 이름 변경
  appspec.yml
Labels: :bug: Bug

#55 :sparkles: [Feat] nginx 설정 및 배포 스크립트 설정
  .platform/nginx.conf
  appspec.yml
  scripts/health_check.sh
  scripts/run_new_was.sh
  scripts/switch.sh
Labels: :sparkles: Feat

#56 :sparkles: [Feat] 환경변수 주입 설정
  build.gradle
  src/main/resources/application.yml
  src/main/resources/bootstrap.yml
Labels: :sparkles: Feat

#57 :recycle: [Refactor] application.yml 수정
  build.gradle
  src/main/java/ssuPlector/controller/RootController.java
  src/main/resources/application.yml
Labels: :recycle: Refactor

#58 :recycle: [Refactor] .sh 코드 리팩토링
  scripts/switch.sh
Labels: :recycle: Refactor, Test

#60 :recycle: [Refactor] after_install.sh 기능 추가
  appspec.yml
  scripts/after_install.sh
Labels: :bug: Bug

#61 :recycle: [Refactor] after_install.sh 기능 수정
  appspec.yml
Labels: :bug: Bug

#65 :recycle: [Refactor] after_install.sh 리팩토링
  scripts/after_install.sh
Labels: :recycle: Refactor, :bug: Bug

#76 ♻️ [Refactor] 개발자 검색 기능 수정
  src/main/java/ssuPlector/aws/s3/AmazonS3Manager.java
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/controller/ProjectController.java
  src/main/java/ssuPlector/converter/DeveloperConverter.java
  src/main/java/ssuPlector/domain/Developer.java
  src/main/java/ssuPlector/dto/request/DeveloperDTO.java
  src/main/java/ssuPlector/dto/request/ProjectDTO.java
  src/main/java/ssuPlector/dto/response/DeveloperDTO.java
  src/main/java/ssuPlector/repository/developer/DeveloperRepositoryCustom.java
  src/main/java/ssuPlector/repository/developer/DeveloperRepositoryImpl.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
  src/main/java/ssuPlector/validation/annotation/MaxSizeTwo.java
  src/test/java/ssuPlector/ProjectServiceTest.java
  src/test/java/ssuPlector/SsuPlectorApplicationTests.java
Labels: :sparkles: Feat, :recycle: Refactor

#77 ✨ [Feat] 카카오 소셜 로그인 구현
  build.gradle
  src/main/java/ssuPlector/config/WebConfig.java
  src/main/java/ssuPlector/controller/AuthController.java
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/controller/ProjectController.java
  src/main/java/ssuPlector/converter/AuthConverter.java
  src/main/java/ssuPlector/domain/Developer.java
  src/main/java/ssuPlector/domain/category/SocialType.java
  src/main/java/ssuPlector/dto/KakaoProfile.java
  src/main/java/ssuPlector/dto/OAuthToken.java
  src/main/java/ssuPlector/dto/response/AuthResponseDTO.java
  src/main/java/ssuPlector/global/response/ApiResponse.java
  src/main/java/ssuPlector/global/response/code/GlobalErrorCode.java
  src/main/java/ssuPlector/redis/domain/RefreshToken.java
  src/main/java/ssuPlector/redis/repository/RefreshTokenRepository.java
  src/main/java/ssuPlector/redis/service/RefreshTokenService.java
  src/main/java/ssuPlector/repository/developer/DeveloperRepository.java
  src/main/java/ssuPlector/security/SecurityConfig.java
  src/main/java/ssuPlector/security/filter/AuthExceptionHandlingFilter.java
  src/main/java/ssuPlector/security/filter/JwtAuthenticationFilter.java
  src/main/java/ssuPlector/security/handler/JwtAccessDeniedHandler.java
  src/main/java/ssuPlector/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/ssuPlector/security/handler/annotation/AuthUser.java
  src/main/java/ssuPlector/security/handler/annotation/ExtractToken.java
  src/main/java/ssuPlector/security/handler/resolver/AuthUserArgumentResolver.java
  src/main/java/ssuPlector/security/handler/resolver/ExtractTokenArgumentResolver.java
  src/main/java/ssuPlector/security/principal/PrincipalDetails.java
  src/main/java/ssuPlector/security/principal/PrincipalDetailsService.java
  src/main/java/ssuPlector/security/provider/JwtTokenProvider.java
  src/main/java/ssuPlector/security/provider/KakaoAuthProvider.java
  src/main/java/ssuPlector/security/test/TestAuthController.java
  src/main/java/ssuPlector/security/test/TestAuthService.java
  src/main/java/ssuPlector/security/test/dto/TestAuthResponse.java
  src/main/java/ssuPlector/service/auth/AuthService.java
  src/main/java/ssuPlector/service/auth/AuthServiceImpl.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: Feat, :recycle: Refactor

#80 ✨ [Feat] 개발자 프로필 생성 api 구현 (2차)
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/converter/AuthConverter.java
  src/main/java/ssuPlector/converter/DeveloperConverter.java
  src/main/java/ssuPlector/domain/Developer.java
  src/main/java/ssuPlector/dto/request/DeveloperDTO.java
  src/main/java/ssuPlector/service/developer/DeveloperService.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
Labels: :sparkles: Feat

#82 :recycle: [Refactor] 개발자 리스트 응답 DTO imageLink 추가
  src/main/java/ssuPlector/converter/DeveloperConverter.java
  src/main/java/ssuPlector/dto/response/DeveloperDTO.java
Labels: :recycle: Refactor

#84 :recycle: [Refactor] 개발자 상세조회 API 응답 DTO 수정
  src/main/java/ssuPlector/converter/ProjectConverter.java
  src/main/java/ssuPlector/domain/Developer.java
  src/main/java/ssuPlector/dto/response/DeveloperDTO.java
  src/main/java/ssuPlector/dto/response/ProjectDTO.java
Labels: :recycle: Refactor

#79 [Feat] 회원 탈퇴 구현
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/domain/Developer.java
  src/main/java/ssuPlector/service/developer/DeveloperService.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
Labels: :sparkles: Feat

#85 ✨ [Feat] 내 개발자 페이지 조회 api 구현 및 조회수 중복 처리 수정
  src/main/java/ssuPlector/controller/AuthController.java
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/security/filter/JwtAuthenticationFilter.java
  src/main/java/ssuPlector/security/handler/resolver/AuthUserArgumentResolver.java
  src/main/java/ssuPlector/security/principal/PrincipalDetails.java
  src/main/java/ssuPlector/security/test/TestAuthService.java
  src/main/java/ssuPlector/service/auth/AuthService.java
  src/main/java/ssuPlector/service/auth/AuthServiceImpl.java
  src/main/java/ssuPlector/service/developer/DeveloperService.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
Labels: :sparkles: Feat, :recycle: Refactor

#86 ✨[Feat] 개발자 프로필 수정 기능 구현
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/controller/ProjectController.java
  src/main/java/ssuPlector/domain/Developer.java
  src/main/java/ssuPlector/dto/request/DeveloperDTO.java
  src/main/java/ssuPlector/service/developer/DeveloperService.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
Labels: :sparkles: Feat

#88 ♻️ [Refactor] 비정상 코드로 접근시 예외처리 / 인증없이 접근시 예외처리
  src/main/java/ssuPlector/security/SecurityConfig.java
  src/main/java/ssuPlector/security/handler/resolver/AuthUserArgumentResolver.java
  src/main/java/ssuPlector/security/provider/KakaoAuthProvider.java
Labels: :recycle: Refactor

#90 ♻️ [Refactor] 프로젝트 생성시 카테고리 리스트 사이즈 고정 설정
  src/main/java/ssuPlector/converter/ProjectConverter.java
  src/main/java/ssuPlector/domain/Developer.java
  src/main/java/ssuPlector/service/BaseMethod.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
  src/main/java/ssuPlector/service/project/ProjectServiceImpl.java
Labels: :recycle: Refactor

#93 Issue/91 chore
  src/main/java/ssuPlector/domain/category/Category.java
  src/main/java/ssuPlector/domain/category/DevLanguage.java
  src/main/java/ssuPlector/domain/category/DevTools.java
  src/main/java/ssuPlector/domain/category/Part.java
  src/main/java/ssuPlector/dto/request/ProjectDTO.java
  src/main/java/ssuPlector/service/project/ProjectServiceImpl.java
Labels: Chore

#94 [Fix] 프로젝트 리스트 조회 Blank 요청 오류 해결
  src/main/java/ssuPlector/repository/project/ProjectRepositoryCustomImpl.java
  src/main/java/ssuPlector/service/project/ProjectServiceImpl.java
Labels: :bug: Bug

#95 [Chore] TechStack ENUM 수정
  src/main/java/ssuPlector/domain/category/TechStack.java
Labels: Chore

#100 ♻️ [Refactor] 카카오 서버에게 토큰 요청하는 과정 삭제 및 액세스 토큰으로 로그인 처리 / 조회수 업데이트 시간 10->30분으로 수정
  src/main/java/ssuPlector/config/SchedulerConfig.java
  src/main/java/ssuPlector/redis/repository/Impl/DeveloperHitsRepositoryImpl.java
  src/main/java/ssuPlector/redis/repository/Impl/ProjectHitsRepositoryImpl.java
  src/main/java/ssuPlector/security/SecurityConfig.java
  src/main/java/ssuPlector/security/provider/KakaoAuthProvider.java
  src/main/java/ssuPlector/service/auth/AuthServiceImpl.java
Labels: :recycle: Refactor

#102 ✨ [Feat] 더미 데이터 생성 api 구현
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/converter/DeveloperConverter.java
  src/main/java/ssuPlector/dto/request/DeveloperDTO.java
  src/main/java/ssuPlector/dto/request/ProjectDTO.java
  src/main/java/ssuPlector/security/SecurityConfig.java
  src/main/java/ssuPlector/service/developer/DeveloperService.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
  src/main/resources/bootstrap.yml
Labels: :sparkles: Feat
