Repository SSU-Plector/SSU-Plector-Backend, pull requests merged in 2024-07, with the labels that each got.

#126 ✨ [Feat] 회의 진행 플로우 추천 API 구현
  src/main/java/ssuPlector/ai/openAI/dto/ChatGptRequest.java
  src/main/java/ssuPlector/ai/openAI/dto/ChatGptResponse.java
  src/main/java/ssuPlector/ai/openAI/dto/Message.java
  src/main/java/ssuPlector/ai/openAI/service/ChatGptService.java
  src/main/java/ssuPlector/ai/openAI/service/ChatGptServiceImpl.java
  src/main/java/ssuPlector/controller/PmController.java
  src/main/java/ssuPlector/domain/category/MeetingTodo.java
  src/main/java/ssuPlector/dto/request/PmDTO.java
  src/main/java/ssuPlector/global/response/code/GlobalErrorCode.java
  src/main/java/ssuPlector/security/SecurityConfig.java
  src/main/java/ssuPlector/service/pm/PmService.java
  src/main/java/ssuPlector/service/pm/PmServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: Feat, :memo: Docs

#125 ✨ [FEAT] 음성 파일 요약 정리 API 구현
  .ebextensions-dev/02-ffmpeg-package.config
  build.gradle
  src/main/java/ssuPlector/ai/naverCloud/service/ClovaService.java
  src/main/java/ssuPlector/ai/naverCloud/service/ClovaServiceImpl.java
  src/main/java/ssuPlector/ai/openAI/service/ChatGptService.java
  src/main/java/ssuPlector/ai/openAI/service/ChatGptServiceImpl.java
  src/main/java/ssuPlector/config/OpenAiConfig.java
  src/main/java/ssuPlector/controller/PmController.java
  src/main/java/ssuPlector/global/response/code/GlobalErrorCode.java
  src/main/java/ssuPlector/security/SecurityConfig.java
  src/main/java/ssuPlector/service/pm/PmService.java
  src/main/java/ssuPlector/service/pm/PmServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: Feat

#130 :recycle: [Refactor] ffmpeg 설치 오류 수정
  .ebextensions-dev/02-ffmpeg-package.config
Labels: :recycle: Refactor, :bug: Bug

#135 ♻️ [Refactor] imageMagic 설치 코드 삭제
  .ebextensions-dev/02-ffmpeg-package.config
Labels: :recycle: Refactor

#136 :recycle: [Refactor] imageMagic 설치 코드 오류 수정
  .ebextensions-dev/02-ffmpeg-package.config
Labels: :recycle: Refactor

#132 :recycle: [Refactor] 회의 진행 반환 값 String에서 시간(ms)만 추출해 리턴
  src/main/java/ssuPlector/controller/PmController.java
  src/main/java/ssuPlector/converter/PmConverter.java
  src/main/java/ssuPlector/dto/response/PmDTO.java
  src/main/java/ssuPlector/service/pm/PmService.java
  src/main/java/ssuPlector/service/pm/PmServiceImpl.java
Labels: :recycle: Refactor

#134 :recycle: [Refactor] 기존에 있던 개발자 검색 후 해당 값 등록
  src/main/java/ssuPlector/dto/request/ProjectDTO.java
  src/main/java/ssuPlector/service/project/ProjectServiceImpl.java
Labels: :recycle: Refactor

#139 ✨ [Feat] 개발자 검색 API 구현 및 요구사항에 따른 ENUM값 업데이트
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/converter/DeveloperConverter.java
  src/main/java/ssuPlector/domain/category/Category.java
  src/main/java/ssuPlector/domain/category/DevLanguage.java
  src/main/java/ssuPlector/domain/category/Part.java
  src/main/java/ssuPlector/dto/response/DeveloperDTO.java
  src/main/java/ssuPlector/repository/developer/DeveloperRepositoryCustom.java
  src/main/java/ssuPlector/repository/developer/DeveloperRepositoryImpl.java
  src/main/java/ssuPlector/security/SecurityConfig.java
  src/main/java/ssuPlector/service/developer/DeveloperService.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
Labels: :sparkles: Feat

#142 ♻️ [Refactor] ClovaSpeech API 사용방식으로 변경
  .ebextensions-dev/02-ffmpeg-package.config
  src/main/java/ssuPlector/ai/naverCloud/service/ClovaService.java
  src/main/java/ssuPlector/ai/naverCloud/service/ClovaServiceImpl.java
  src/main/java/ssuPlector/ai/naverCloud/service/ClovaSpeechService.java
  src/main/java/ssuPlector/ai/naverCloud/service/ClovaSpeechServiceImpl.java
  src/main/java/ssuPlector/ai/openAI/service/ChatGptServiceImpl.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
  src/main/java/ssuPlector/service/pm/PmServiceImpl.java
  src/main/resources/application.yml
Labels: :recycle: Refactor, :bug: Bug

#146 :sparkles: [Feat] 더미 개발자 프로필 수정 API
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/security/SecurityConfig.java
Labels: :sparkles: Feat

#149 :recycle: [Refactor] 트랜잭션 처리 추가
  src/main/java/ssuPlector/controller/ProjectController.java
  src/main/java/ssuPlector/service/project/ProjectServiceImpl.java
Labels: :recycle: Refactor

#151 ✨ [Feat] 유저의 입력 값 바탕 제일 높은 가중치의 개발자 3명 반환하는 API
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/dto/request/DeveloperDTO.java
  src/main/java/ssuPlector/repository/developer/DeveloperRepositoryCustom.java
  src/main/java/ssuPlector/repository/developer/DeveloperRepositoryImpl.java
  src/main/java/ssuPlector/security/SecurityConfig.java
  src/main/java/ssuPlector/service/developer/DeveloperService.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: Feat

#152 :wrench: [Refactor] 설정 경로 수정
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
Labels: :recycle: Refactor

#154 ♻️ [Refactor] AI 서버에서 전달받은 유사도로 정확도 높이도록 변경
  src/main/java/ssuPlector/controller/DeveloperController.java
  src/main/java/ssuPlector/global/response/code/GlobalErrorCode.java
  src/main/java/ssuPlector/repository/developer/DeveloperRepositoryImpl.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
Labels: :sparkles: Feat, :recycle: Refactor

#156 :recycle: [Refactor] 매칭 시 적합한 개발자가 없을 때 true 반환, 기타 오류는 false 및 에러 코드 반환
  src/main/java/ssuPlector/repository/developer/DeveloperRepositoryCustom.java
  src/main/java/ssuPlector/repository/developer/DeveloperRepositoryImpl.java
  src/main/java/ssuPlector/service/developer/DeveloperServiceImpl.java
Labels: :recycle: Refactor
